import { Injectable } from '@angular/core';
import { Recipe } from '@models/recipe';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  constructor() {}

  recipes: Recipe[] = [
    {
      id: 1,
      imageLink: 'https://i.redd.it/k31tprm0cnz31.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Jabbos Famous Pizza From Italy',
      avgRating: 5,
      numberOfReviews: 120,
      category: 'sicilian',
    },
    {
      id: 2,
      imageLink: 'https://i.redd.it/nzuztqgvpdv31.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: "Helen's homemade Pizza",
      avgRating: 5,
      numberOfReviews: 120,
      category: 'sicilian',
    },
    {
      id: 3,
      imageLink: 'https://i.redd.it/7n3tuetejnm41.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Jimmys Neopolitan',
      avgRating: 5,
      numberOfReviews: 120,
      category: 'sicilian',
    },
    {
      id: 4,
      imageLink: 'https://i.redd.it/1f8such8r4q41.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Chicago Recipe 1',
      avgRating: 5,
      numberOfReviews: 120,
      category: 'chicago',
    },
    {
      id: 5,
      imageLink: 'https://i.imgur.com/veuFBTG.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Chicago Recipe 2',
      avgRating: 5,
      numberOfReviews: 120,
      category: 'chicago',
    },
    {
      id: 6,
      imageLink: 'https://i.redd.it/845ibu1l4yzy.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Chicago Recipe 3',
      avgRating: 5,
      numberOfReviews: 120,
      category: 'chicago',
    },
    {
      id: 7,
      imageLink: 'https://i.redd.it/1f8such8r4q41.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Chicago Recipe 4',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'chicago',
    },
    {
      id: 8,
      imageLink: 'https://i.imgur.com/veuFBTG.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Chicago Recipe 5',
      avgRating: 8,
      numberOfReviews: 120,
      category: 'chicago',
    },
    {
      id: 9,
      imageLink: 'https://i.redd.it/845ibu1l4yzy.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Chicago Recipe 6',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'chicago',
    },
    {
      id: 10,
      imageLink: 'https://i.redd.it/8fsbooeyihp41.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Detroit 1',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'detroit',
    },
    {
      id: 11,
      imageLink: 'https://i.redd.it/472jhzg2x5w31.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Detroit 2',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'detroit',
    },
    {
      id: 12,
      imageLink: 'https://i.redd.it/f8uxnjrz7ol41.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Detroit 3',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'detroit',
    },
    {
      id: 13,
      imageLink: 'https://i.redd.it/8fsbooeyihp41.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Detroit 4',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'detroit',
    },
    {
      id: 14,
      imageLink: 'https://i.redd.it/472jhzg2x5w31.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Detroit 5',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'detroit',
    },
    {
      id: 15,
      imageLink: 'https://i.redd.it/f8uxnjrz7ol41.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Detroit 6',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'detroit',
    },
    {
      id: 16,
      imageLink: 'https://i.imgur.com/JyMi64O.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Neopolitan 1',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'neopolitan',
    },
    {
      id: 17,
      imageLink: 'https://i.imgur.com/YdOYxbw.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Neopolitan 2',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'neopolitan',
    },
    {
      id: 18,
      imageLink: 'https://i.redd.it/6l1oq4zp51l31.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Neopolitan 3',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'neopolitan',
    },
    {
      id: 19,
      imageLink: 'https://i.imgur.com/JyMi64O.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Neopolitan 4',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'neopolitan',
    },
    {
      id: 20,
      imageLink: 'https://i.imgur.com/YdOYxbw.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Neopolitan 5',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'neopolitan',
    },
    {
      id: 21,
      imageLink: 'https://i.redd.it/6l1oq4zp51l31.jpg',
      prepTime: '20 min',
      activeTime: '20 min',
      title: 'Neopolitan 6',
      avgRating: 4,
      numberOfReviews: 120,
      category: 'neopolitan',
    },
  ];

  getAllRecipes(): Recipe[] {
    return this.recipes;
  }
}
